apiVersion: v1
kind: Service
metadata:
  name: go-project-kong-service
  namespace: go-project-kong-namespace
spec:
  type: NodePort
  selector:
    app: go-project-kong
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30001
